### ISSUE TITLE
Preprocessing for NVGesture Dataset

### ISSUE THREAD

**Issue by saurabbhsp** [okankop/MFF-pytorch#11]
Hi,
Can you also share the preprocessing script/steps for NVGesture dataset. How different is the process than the jester dataset.

**Comment by okankop** [comment]
it is exactly same as Jester dataset. You need to use [process_dataset.py](process_dataset.py) to generate following files:
category.txt:               the list of categories.
train_videofolder.txt:  each row contains [videoname num_frames classIDX]
val_videofolder.txt:    same as above
