### ISSUE TITLE
Training code hangs for Jester Dataset

### ISSUE THREAD

**Issue by saidwivedi** [okankop/MFF-pytorch#4]
When I run the training from scratch code for Jester dataset with the following command -

> CUDA_VISIBLE_DEVICES=1,2 python main.py jester RGB --batch-size 32 --workers=1

The code hangs at [https://github.com/okankop/MFF-pytorch/blob/master/main.py#L169](https://github.com/okankop/MFF-pytorch/blob/master/main.py#L169)
Am I missing something ?

I am using Python 3.6 and Pytorch 0.3.1

**Comment by okankop** [comment]
I have just fixed the issue. Now, the code is compatible for also RGB and Flow modalities. Could you please reclone the code and try?

**Comment by saidwivedi** [comment]
@okankop  Yes I pulled the latest changes and it works. Thanks a lot for your quick response.

**Comment by xiaofeiwu** [comment]
@okankop I still meet this issue, could you let me know why?

**Comment by okankop** [comment]
@xiaofeiwu Could you please check if the __getitem__(self, index) in dataset.py is functioning properly? Your code might be stucking at lines 118 or 122 in dataset.py.
