### ISSUE TITLE
RuntimeError: invalid argument 2: size '[-1 x 8 x 256]' is invalid for input with 512 elements 

### ISSUE THREAD

**Issue by 0x10cxR1** [okankop/MFF-pytorch#5]
Hi there,

when using test_models.py, I got an error showing as:

RuntimeError: invalid argument 2: size '[-1 x 8 x 256]' is invalid for input with 512 elements at /pytorch/torch/lib/TH/THStorage.c:37

it happens in the eval_video function. I'm using the pretrained models and testing on jester. Both models have this kind of issues. How should I fix that? 

Thanks!

**Comment by 0x10cxR1** [comment]
Problem solved! I forgot to change the batch_size in the testing, or set to just use 1 GPU when running the python.

**Comment by cjtang** [comment]
@0x10cxR1  Hi, I met the same issue during testing the pretrained model. May I ask what did you change in the code? I see in the code batch_size is already set to 1.
