### ISSUE TITLE
input specifities

### ISSUE THREAD

**Issue by Omenranr** [okankop/MFF-pytorch#7]
Hello, I'm trying to feed the pretrained model to get prediction, but I have some problems with data preprocessing. I'm wondering what is the input specifities: size, how much frames, type ?

the test_videos.py file in TRN repository gives: torch.Size([1, 80, 3, 224, 224])

**Comment by okankop** [comment]
Can you please write your question more clearly? If you look at the code for validation, you would see how a video is preprocessed to get its prediction.

**Comment by Omenranr** [comment]
ok thank you
